Anniken20/workshop

Assets/Settings/URP-Balanced.asset
Assets/Settings/URP-Performant.asset
Assets/StarterAssets/Environment/Art/Materials/Blue_Mat.mat
Assets/StarterAssets/Environment/Art/Materials/GreyBlue_Mat.mat
Assets/StarterAssets/Environment/Art/Materials/GridBlue_01_Mat.mat
Assets/StarterAssets/ThirdPersonController/Scenes/Anniken test.unity
Assets/StarterAssets/ThirdPersonController/Scenes/Anniken test.unity.meta
Assets/StarterAssets/ThirdPersonController/Scenes/Playground.unity
ProjectSettings/TagManager.asset

Generally testing our the iso view

Isometric view test

---

Assets/Scenes/Prototypes/GameplayPrototype.unity

lasso can crash unity sometimes b careful for rn

Lasso added to gameproto

---

Assets/Scenes/Prototypes/GameplayPrototype.unity

Revert "Fix Controller"

---

Assets/Scenes/Main Game scenes/Level 1.unity

- tried out barn and inn puzzle ideas for lasso and ricochet
- extraneous puzzle testing
- implementing caden's new aiming stuff to lvl1

lvl 1 messing around

---

Assets/Scenes/Main Game scenes/Level 1.unity

level 1 organized

---

Assets/FULLSCREEN/FULLSCREEN TEST.unity
Assets/FULLSCREEN/Fullscreen.mat
Assets/FULLSCREEN/Fullscreen.shadergraph
Assets/Settings/URP-HighFidelity-Renderer.asset

shader ghost fullscreen update

---

Assets/Scenes/Main Game scenes/Level 1.unity

basic map for level 1 outlined (working on adding verticality to the level)

level 1 map update

---

Assets/EthanStuff/Sticky.physicMaterial
Assets/EthanStuff/Sticky.physicMaterial.meta
Assets/Scenes/Main Game scenes/Level 1.unity

- adjusted jump height to 2
- adjusted player gravity to -45
- adjusted drag to 1 (actually cant tell if that did anything)
- increased move speed to 9

player adjustments mostly

---

Assets/Level Elements/1door parent.prefab
Assets/Level Elements/1door parent.prefab.meta
Assets/Level Elements/2pressure plate door parent.prefab
Assets/Level Elements/2pressure plate door parent.prefab.meta
Assets/Level Elements/3shoot obj door parent.prefab
Assets/Level Elements/3shoot obj door parent.prefab.meta
Assets/Level Elements/NEW_Teleporter InOut.prefab
Assets/Level Elements/NEW_Teleporter InOut.prefab.meta
Assets/Level Elements/TeleportIn.prefab
Assets/Level Elements/TeleportIn.prefab.meta
Assets/Scenes/Main Game scenes/Level 1.unity

- areas blocked out for basic  enemy combat, lasso tutorial, and connector to town via side path
- added teleporters for the 3 main buildings for level 1 (interiors unfinished)

Tutorial area finished connected to lvl1

---

Assets/Prefabs/TeleportIn.prefab.meta
Assets/Scenes/Main Game scenes/Level 1.unity

- remade teleporter prefab to not be sucky
- 2 way teleporters to all interiors (quality of the interiors notwithstanding)

little more touch up

---

Assets/Scenes/Main Game scenes/Level 1.unity

organization, coins, fade/walk tele. in lvl1

---

Assets/EthanStuff/DitherWood.mat
Assets/LukeTesting/Materials/Testing_Lasso_Mat.mat
Assets/Materials/Val/Lasso/Lasso.mat
Assets/Materials/Val/Lasso/LassoRenderer.mat
Assets/Materials/Val/ToonBraid.mat
Assets/Scenes/Main Game scenes/Level 1.unity

-altered dither material
-swapped lasso mats to lit toon so they display correctly -swapped val's braid to lit toon so it displays properly

material stuffs

---

Assets/3D Models/Miscellaneous/Buildings/Barn Collision.prefab
Assets/3D Models/Miscellaneous/Buildings/Barn Collision.prefab.meta
Assets/3D Models/Miscellaneous/Buildings/Inn_collision.prefab
Assets/3D Models/Miscellaneous/Buildings/Inn_collision.prefab.meta
Assets/3D Models/Miscellaneous/Buildings/Saloon Collision.prefab
Assets/3D Models/Miscellaneous/Buildings/Saloon Collision.prefab.meta
Assets/3D Models/Miscellaneous/Buildings/clocktower Variant.prefab
Assets/3D Models/Miscellaneous/Buildings/clocktower Variant.prefab.meta
Assets/Scenes/Main Game scenes/Level 1.unity

-inn/hotel/ranch w/ collisions prefab
-little bit of level 1 stuff

prefabbed the VS buildings

---

Assets/3D Models/Miscellaneous/Rocks/RockFormation2_Normal_Raw.1001.png.meta
Assets/Scenes/Main Game scenes/Level 1.unity

Adjusted bottle ricochet puzzles and made minimap higher to show more

Minor Level 1 Adjustments

---

Assets/Materials/New Material.mat
Assets/Materials/New Material.mat.meta
Assets/Materials/Particles/DashedLine(LitToon)Hopefully.mat
Assets/Materials/Particles/DashedLine(LitToon)Hopefully.mat.meta
Assets/Scenes/Main Game scenes/Level 1.unity

- new encounters for the side paths (1 lasso, 1 basic combat, 1 lasso & ricochet) that each reward barrels full of money (
- dashed line sort of restored on aim line (still kinda ass tho)
- collision on buildings, level mostly closed in (hopefully), everything in level is accessible (some a bit more out of the way due to lack of teleporters atm), -QTE is "in the level", just needs the boss in order to work, but wanted to wait till I had some oversight to make sure the Ai gets inserted into the level correctly.

level 1 mostly complete

---

Assets/Prefabs/GhostSpawner.prefab
Assets/Scripts/GhostSpawner.cs

Ghost enemies now spawn at same height and can be set to spawn at different location from trigger

Ghost Enemy Fix

---

Assets/Scenes/Main Game scenes/Level 2.unity.meta

Level 2 graybox

---

Assets/Team/Materials.meta
Assets/Team/Materials/caden.mat
Assets/Team/Materials/caden.mat.meta

Level 2 has, like, many stuffs put in and it's, like, kinda coolish.  I hope you guys like.  :)

Level 2 graybox commit

---

Assets/EthanStuff/LVL2 Puzzles.unity
Assets/Materials/Saloon/Chair/Chair.fbx.meta
Assets/Prefabs/Saloon Props/Chair Variant 1.prefab
Assets/Prefabs/Saloon Props/Chair Variant 1.prefab.meta
Assets/Prefabs/Saloon Props/Relies on goofy ahh chair.prefab
Assets/Prefabs/Saloon Props/Relies on goofy ahh chair.prefab.meta
Assets/Prefabs/Saloon Props/goofy ahh big chair DONT USE.prefab
Assets/Prefabs/Saloon Props/goofy ahh big chair DONT USE.prefab.meta
Assets/Scripts/Enemy Types/BasicGhostEnemy.cs
ProjectSettings/TagManager.asset

- looks at player (so works with the shield)
- changed deal damage to ontriggerstay
- rudimentary haunted chair using same script

ghost enemy mess around

---

Assets/Scenes/Main Game scenes/Level 1.unity
Assets/Scenes/Main Game scenes/Tutorial 1.unity

Will do tomorrow.  Am eepifying.

Setup for Level 1 Set Dressing

---

Assets/Scenes/Main Game scenes/Level 1.unity
Assets/Sprites/Church InteriorExterior/crypt bump 1.png.meta
Assets/Sprites/Church InteriorExterior/seamless stone normal 1.png.meta
Assets/Sprites/Church InteriorExterior/seamless wood normal.png.meta

Made some tiny changes to level 1

Minor Level 1 Changes

---

Assets/Scenes/Main Game scenes/Level 1.unity

Level 1 Pushes

---

Assets/Scenes/Main Game scenes/Level 2.unity

- organized sections mostly
- checkpoints added
- bs'd kill planes in the giant pit in crypt

lvl 2 updates and upkeep

---

Assets/Scenes/Main Game scenes/Tutorial 1.unity

Fixed some errors with map boundaries
Cacti stayed gone :(

Tutorial 1 commit

---

Assets/Scenes/Main Game scenes/HUB.unity
Assets/Scenes/Main Game scenes/Level 2.unity
Assets/Scenes/Main Game scenes/Tutorial 1.unity

Minor Final Changes

---

Assets/Scenes/Main Game scenes/HUB.unity

Checkpoint Fixes Level 1

---

ProjectSettings/QualitySettings.asset

- Added Enrique's pre-battle dialogue

Adding Enrique Dialogue

---

Assets/Shaders/ScrollingDashedLine.mat
ProjectSettings/ProjectSettings.asset

To fix things that'd break for players

Temp Fix to Level 3

---

Assets/Scripts/NPC/DialoguePopupController.cs

Removed audio pops

---

Assets/Amadin/LevelManager.cs
Assets/LukeTesting/LukeTestingScripts/SavingandLoading/DataManager.cs
Assets/Scenes/Main Game scenes/HUB.unity
Assets/Scripts/SceneTeleport.cs

Fixed Level Manager to proper update NPCs

Level Manager Fix

---

Assets/Scenes/Main Game scenes/HUB.unity

Make sure new NPCs with dialogue have audio source

Minor NPC fix

---

Assets/Prefabs/Menus/PauseMenu.prefab
Assets/Scenes/Main Game scenes/Tutorial 1.unity

Minor audio changes

---

Assets/Shaders/ScrollingDashedLine.mat

Final level 2 changes

---

Assets/Level Elements/Breakable_Barrel.prefab
Assets/Scenes/Main Game scenes/Tutorial 1.unity
Assets/Shaders/ScrollingDashedLine.mat

Tutorial should be mostly set now

Minor Tutorial Fixes

---

Assets/Scenes/Main Game scenes/HUB.unity
Assets/Shaders/GhostUnlitAttemptRED.mat
Assets/Shaders/GhostUnlitAttemptRED.mat.meta

- jordan doors fixed
- evil ghost shader created
- hub lamp poles material changed
- no more stink cloud in hub

in class changes

---

Assets/Dissolver.cs
Assets/Dissolver.cs.meta

Dissolver :)

---

Assets/Scripts/Enemies/Enemy.cs
Assets/Scripts/Enemies/Enrique.cs
Assets/Shaders/ScrollingDashedLine.mat

Varied Enemy SFX Lvl 1

---

Assets/Prefabs/Demos/CheckpointCube.prefab

Checkpoints now say we autosaved :D

Autosave Push

---

Assets/Scripts/Enemies/Minor Enemies/BasicGhostEnemy.cs

No More teleport.  If you don't like this change, ya'll can uncomment it.

Addition Basic Ghost Fix

---

Assets/EnriqueDiedYouDoToo.cs
Assets/Scripts/Enemies/Minor Enemies/BasicGhostEnemyEnrique.cs.meta

I'm gonna krill myself

---

Assets/Custscenes/Videos/V2 Cutscenes.meta
Assets/Custscenes/Videos/V2 Cutscenes/CallToAction_WithSFX.mp4.meta
Assets/Custscenes/Videos/V2 Cutscenes/FinalCutscene.mp4.meta
Assets/Custscenes/Videos/V2 Cutscenes/FlashbackCutscene1.mp4.meta
Assets/Custscenes/Videos/V2 Cutscenes/FlashbackCutscene2.mp4.meta
Assets/Custscenes/Videos/V2 Cutscenes/FlashbackCutscene3.mp4.meta
Assets/Custscenes/Videos/V2 Cutscenes/IntroCutscene_WithSFX.mp4.meta
Assets/Custscenes/Videos/V2 Cutscenes/LowPoint_WithSFX.mp4.meta
Assets/Scenes/Cutscenes/CallToActionCutscene_MP4.unity
Assets/Scenes/Cutscenes/FightCutscene_MP4.unity
Assets/Scenes/Cutscenes/FinalCutscene_MP4.unity
Assets/Scenes/Cutscenes/IntroCutscene_MP4.unity
Assets/Scenes/Cutscenes/LowPointCutscene_MP4.unity

Still need proper in-scene integration I think

Added and replace cutscenes

---

Assets/BrianTestScripts/BrianTestScripts/VideoController.cs
Assets/QTE/QTEDuel.cs

Pushing Level 3 Final Cutscene stuff

---

Assets/QTE/QTEDuel.cs

Tiny Level 1 Carillo Fix

---

Assets/Prefabs/Enemy Bullet 1.prefab
Assets/Scripts/Enemies/State Machine/States/Daughter-Data/DaughterShootData.asset
Assets/Scripts/Projectiles/EnemyBullet.cs
Assets/Shaders/ScrollingDashedLine.mat

Fixed minor poppy stuff and bullets not disappearing

Level 2 minor commit

---

Assets/BrianTestScripts/BrianTestScripts/VideoController.cs
Assets/QTE/QTEDuel.cs

No more running during dialogue

Dialogue Unfreeze Fix

---

Assets/Scenes/Main Game scenes/Tutorial 1.unity
Assets/Scripts/NPC/DialoguePopupController.cs

Fixed tutorial issues

---

Assets/Level Elements/NOTES/Level 1 Notes/Tutorial1Note.asset
Assets/Level Elements/NOTES/Level 1 Notes/Tutorial1Note.asset.meta
Assets/Scenes/Main Game scenes/Tutorial 1.unity

Tutorial Note Fix

---

Assets/Scripts/NPC/DialoguePopupController.cs

Dialogue fix again

---

Assets/BrianTestScripts/BrianTestScripts/SwitchController.cs

Fixed issue with repeating click noise

Switch SFX Improvement

---

Assets/BrianTestScripts/Notes/NotesSystem.cs
Assets/Scenes/Main Game scenes/Tutorial 1.unity
Assets/Scripts/Enemy Death Checkers.meta
Assets/Scripts/Enemy Death Checkers/EnemyDeathChecker.cs
Assets/Scripts/Enemy Death Checkers/EnemyDeathChecker.cs.meta
Assets/Scripts/Enemy Death Checkers/EnemyDeathCheckerUniversal.cs
Assets/Scripts/Enemy Death Checkers/EnemyDeathCheckerUniversal.cs.meta
Assets/Scripts/Enemy Death Checkers/EnriqueDeathChecker.cs
Assets/Scripts/Enemy Death Checkers/EnriqueDeathChecker.cs.meta
Assets/Scripts/Enemy Death Checkers/Ghost Wall Disabler.meta
Assets/Scripts/Enemy Death Checkers/Ghost Wall Disabler/GhostWallDisabler1.cs
Assets/Scripts/Enemy Death Checkers/Ghost Wall Disabler/GhostWallDisabler1.cs.meta

Level 1 Fuck up Pass

---

Assets/Scenes/Main Game scenes/Tutorial 1.unity

Level 2 Idiot Proofing

---

Assets/BrianTestScripts/BrianTestScripts/ShadowController.cs

Minor level 3 fixes
